site_name: Propuesta Constitucional
site_url: https://nuevaconstitucion.laconstitucionesnuestra.cl

extra:
  homepage: https://nuevaconstitucion.laconstitucionesnuestra.cl/introduccion/

theme:
  name: material
  language: es
  logo: assets/logo.png
  favicon: assets/logo.png
  font:
    text: Raleway

  palette:
    primary: white
    accent: blue

nav:
  - Introducción: introduccion.md
  - Preámbulo: preambulo.md
 
  - Principios y disposiciones generales:
    - Artículo 1: capitulo1/articulo1.md
    - Artículo 2: capitulo1/articulo2.md
    - Artículo 3: capitulo1/articulo3.md
    - Artículo 4: capitulo1/articulo4.md
    - Artículo 5: capitulo1/articulo5.md
    - Artículo 6: capitulo1/articulo6.md
    - Artículo 7: capitulo1/articulo7.md
    - Artículo 8: capitulo1/articulo8.md
    - Artículo 9: capitulo1/articulo9.md
    - Artículo 10: capitulo1/articulo10.md
    - Artículo 11: capitulo1/articulo11.md
    - Artículo 12: capitulo1/articulo12.md
    - Artículo 13: capitulo1/articulo13.md
    - Artículo 14: capitulo1/articulo14.md
    - Artículo 15: capitulo1/articulo15.md
    - Artículo 16: capitulo1/articulo16.md
  
  - Derechos fundamentales y garantías:
    - Artículo 17: capitulo2/articulo17.md
    - Artículo 18: capitulo2/articulo18.md
    - Artículo 19: capitulo2/articulo19.md
    - Artículo 20: capitulo2/articulo20.md
    - Artículo 21: capitulo2/articulo21.md
    - Artículo 22: capitulo2/articulo22.md
    - Artículo 23: capitulo2/articulo23.md
    - Artículo 24: capitulo2/articulo24.md
    - Artículo 25: capitulo2/articulo25.md
    - Artículo 26: capitulo2/articulo26.md
    - Artículo 27: capitulo2/articulo27.md
    - Artículo 28: capitulo2/articulo28.md
    - Artículo 29: capitulo2/articulo29.md
    - Artículo 30: capitulo2/articulo30.md
    - Artículo 31: capitulo2/articulo31.md
    - Artículo 32: capitulo2/articulo32.md
    - Artículo 33: capitulo2/articulo33.md
    - Artículo 34: capitulo2/articulo34.md
    - Artículo 35: capitulo2/articulo35.md
    - Artículo 36: capitulo2/articulo36.md
    - Artículo 37: capitulo2/articulo37.md
    - Artículo 38: capitulo2/articulo38.md
    - Artículo 39: capitulo2/articulo39.md
    - Artículo 40: capitulo2/articulo40.md
    - Artículo 41: capitulo2/articulo41.md
    - Artículo 42: capitulo2/articulo42.md
    - Artículo 43: capitulo2/articulo43.md
    - Artículo 44: capitulo2/articulo44.md
    - Artículo 45: capitulo2/articulo45.md
    - Artículo 46: capitulo2/articulo46.md
    - Artículo 47: capitulo2/articulo47.md
    - Artículo 48: capitulo2/articulo48.md
    - Artículo 49: capitulo2/articulo49.md
    - Artículo 50: capitulo2/articulo50.md
    - Artículo 51: capitulo2/articulo51.md
    - Artículo 52: capitulo2/articulo52.md
    - Artículo 53: capitulo2/articulo53.md
    - Artículo 54: capitulo2/articulo54.md
    - Artículo 55: capitulo2/articulo55.md
    - Artículo 56: capitulo2/articulo56.md
    - Artículo 57: capitulo2/articulo57.md
    - Artículo 58: capitulo2/articulo58.md
    - Artículo 59: capitulo2/articulo59.md
    - Artículo 60: capitulo2/articulo60.md
    - Artículo 61: capitulo2/articulo61.md
    - Artículo 62: capitulo2/articulo62.md
    - Artículo 63: capitulo2/articulo63.md
    - Artículo 64: capitulo2/articulo64.md
    - Artículo 65: capitulo2/articulo65.md
    - Artículo 66: capitulo2/articulo66.md
    - Artículo 67: capitulo2/articulo67.md
    - Artículo 68: capitulo2/articulo68.md
    - Artículo 69: capitulo2/articulo69.md
    - Artículo 70: capitulo2/articulo70.md
    - Artículo 71: capitulo2/articulo71.md
    - Artículo 72: capitulo2/articulo72.md
    - Artículo 73: capitulo2/articulo73.md
    - Artículo 74: capitulo2/articulo74.md
    - Artículo 75: capitulo2/articulo75.md
    - Artículo 76: capitulo2/articulo76.md
    - Artículo 77: capitulo2/articulo77.md
    - Artículo 78: capitulo2/articulo78.md
    - Artículo 79: capitulo2/articulo79.md
    - Artículo 80: capitulo2/articulo80.md
    - Artículo 81: capitulo2/articulo81.md
    - Artículo 82: capitulo2/articulo82.md
    - Artículo 83: capitulo2/articulo83.md
    - Artículo 84: capitulo2/articulo84.md
    - Artículo 85: capitulo2/articulo85.md
    - Artículo 86: capitulo2/articulo86.md
    - Artículo 87: capitulo2/articulo87.md
    - Artículo 88: capitulo2/articulo88.md
    - Artículo 89: capitulo2/articulo89.md
    - Artículo 90: capitulo2/articulo90.md
    - Artículo 91: capitulo2/articulo91.md
    - Artículo 92: capitulo2/articulo92.md
    - Artículo 93: capitulo2/articulo93.md
    - Artículo 94: capitulo2/articulo94.md
    - Artículo 95: capitulo2/articulo95.md
    - Artículo 96: capitulo2/articulo96.md
    - Artículo 97: capitulo2/articulo97.md
    - Artículo 98: capitulo2/articulo98.md
    - Artículo 99: capitulo2/articulo99.md
    - Artículo 100: capitulo2/articulo100.md
    - Artículo 101: capitulo2/articulo101.md
    - Artículo 102: capitulo2/articulo102.md
    - Artículo 103: capitulo2/articulo103.md
    - Artículo 104: capitulo2/articulo104.md
    - Artículo 105: capitulo2/articulo105.md
    - Artículo 106: capitulo2/articulo106.md
    - Artículo 107: capitulo2/articulo107.md
    - Artículo 108: capitulo2/articulo108.md
    - Artículo 109: capitulo2/articulo109.md
    - Artículo 110: capitulo2/articulo110.md
    - Artículo 111: capitulo2/articulo111.md
    - Artículo 112: capitulo2/articulo112.md
    - Artículo 113: capitulo2/articulo113.md
    - Artículo 114: capitulo2/articulo114.md
    - Artículo 115: capitulo2/articulo115.md
    - Artículo 116: capitulo2/articulo116.md
    - Artículo 117: capitulo2/articulo117.md
    - Artículo 118: capitulo2/articulo118.md
    - Artículo 119: capitulo2/articulo119.md
    - Artículo 120: capitulo2/articulo120.md
    - Artículo 121: capitulo2/articulo121.md
    - Artículo 122: capitulo2/articulo122.md
    - Artículo 123: capitulo2/articulo123.md
    - Artículo 124: capitulo2/articulo124.md
    - Artículo 125: capitulo2/articulo125.md
    - Artículo 126: capitulo2/articulo126.md

  - Naturaleza y medioambiente:
    - Artículo 127: capitulo3/articulo127.md
    - Artículo 128: capitulo3/articulo128.md
    - Artículo 129: capitulo3/articulo129.md
    - Artículo 130: capitulo3/articulo130.md
    - Artículo 131: capitulo3/articulo131.md
    - Artículo 132: capitulo3/articulo132.md
    - Artículo 133: capitulo3/articulo133.md
    - Artículo 134: capitulo3/articulo134.md
    - Artículo 135: capitulo3/articulo135.md
    - Artículo 136: capitulo3/articulo136.md
    - Artículo 137: capitulo3/articulo137.md
    - Artículo 138: capitulo3/articulo138.md
    - Artículo 139: capitulo3/articulo139.md
    - Artículo 140: capitulo3/articulo140.md
    - Artículo 141: capitulo3/articulo141.md
    - Artículo 142: capitulo3/articulo142.md
    - Artículo 143: capitulo3/articulo143.md
    - Artículo 144: capitulo3/articulo144.md
    - Artículo 145: capitulo3/articulo145.md
    - Artículo 146: capitulo3/articulo146.md
    - Artículo 147: capitulo3/articulo147.md
    - Artículo 148: capitulo3/articulo148.md
    - Artículo 149: capitulo3/articulo149.md
    - Artículo 150: capitulo3/articulo150.md

  - Participación democrática:
    - Artículo 151: capitulo4/articulo151.md
    - Artículo 152: capitulo4/articulo152.md
    - Artículo 153: capitulo4/articulo153.md
    - Artículo 154: capitulo4/articulo154.md
    - Artículo 155: capitulo4/articulo155.md
    - Artículo 156: capitulo4/articulo156.md
    - Artículo 157: capitulo4/articulo157.md
    - Artículo 158: capitulo4/articulo158.md
    - Artículo 159: capitulo4/articulo159.md
    - Artículo 160: capitulo4/articulo160.md
    - Artículo 161: capitulo4/articulo161.md
    - Artículo 162: capitulo4/articulo162.md
    - Artículo 163: capitulo4/articulo163.md
    - Artículo 164: capitulo4/articulo164.md

  - Buen gobierno y función pública:
    - Artículo 165: capitulo5/articulo165.md
    - Artículo 166: capitulo5/articulo166.md
    - Artículo 167: capitulo5/articulo167.md
    - Artículo 168: capitulo5/articulo168.md
    - Artículo 169: capitulo5/articulo169.md
    - Artículo 170: capitulo5/articulo170.md
    - Artículo 171: capitulo5/articulo171.md
    - Artículo 172: capitulo5/articulo172.md
    - Artículo 173: capitulo5/articulo173.md
    - Artículo 174: capitulo5/articulo174.md
    - Artículo 175: capitulo5/articulo175.md
    - Artículo 176: capitulo5/articulo176.md
    - Artículo 177: capitulo5/articulo177.md
    - Artículo 178: capitulo5/articulo178.md
    - Artículo 179: capitulo5/articulo179.md
    - Artículo 180: capitulo5/articulo180.md
    - Artículo 181: capitulo5/articulo181.md
    - Artículo 182: capitulo5/articulo182.md
    - Artículo 183: capitulo5/articulo183.md
    - Artículo 184: capitulo5/articulo184.md
    - Artículo 185: capitulo5/articulo185.md
    - Artículo 186: capitulo5/articulo186.md

  - Estado regional y organización territorial:
    - Artículo 187: capitulo6/articulo187.md
    - Artículo 188: capitulo6/articulo188.md
    - Artículo 189: capitulo6/articulo189.md
    - Artículo 190: capitulo6/articulo190.md
    - Artículo 191: capitulo6/articulo191.md
    - Artículo 192: capitulo6/articulo192.md
    - Artículo 193: capitulo6/articulo193.md
    - Artículo 194: capitulo6/articulo194.md
    - Artículo 195: capitulo6/articulo195.md
    - Artículo 196: capitulo6/articulo196.md
    - Artículo 197: capitulo6/articulo197.md
    - Artículo 198: capitulo6/articulo198.md
    - Artículo 199: capitulo6/articulo199.md
    - Artículo 200: capitulo6/articulo200.md
    - Artículo 201: capitulo6/articulo201.md
    - Artículo 202: capitulo6/articulo202.md
    - Artículo 203: capitulo6/articulo203.md
    - Artículo 204: capitulo6/articulo204.md
    - Artículo 205: capitulo6/articulo205.md
    - Artículo 206: capitulo6/articulo206.md
    - Artículo 207: capitulo6/articulo207.md
    - Artículo 208: capitulo6/articulo208.md
    - Artículo 209: capitulo6/articulo209.md
    - Artículo 210: capitulo6/articulo210.md
    - Artículo 211: capitulo6/articulo211.md
    - Artículo 212: capitulo6/articulo212.md
    - Artículo 213: capitulo6/articulo213.md
    - Artículo 214: capitulo6/articulo214.md
    - Artículo 215: capitulo6/articulo215.md
    - Artículo 216: capitulo6/articulo216.md
    - Artículo 217: capitulo6/articulo217.md
    - Artículo 218: capitulo6/articulo218.md
    - Artículo 219: capitulo6/articulo219.md
    - Artículo 220: capitulo6/articulo220.md
    - Artículo 221: capitulo6/articulo221.md
    - Artículo 222: capitulo6/articulo222.md
    - Artículo 223: capitulo6/articulo223.md
    - Artículo 224: capitulo6/articulo224.md
    - Artículo 225: capitulo6/articulo225.md
    - Artículo 226: capitulo6/articulo226.md
    - Artículo 227: capitulo6/articulo227.md
    - Artículo 228: capitulo6/articulo228.md
    - Artículo 229: capitulo6/articulo229.md
    - Artículo 230: capitulo6/articulo230.md
    - Artículo 231: capitulo6/articulo231.md
    - Artículo 232: capitulo6/articulo232.md
    - Artículo 233: capitulo6/articulo233.md
    - Artículo 234: capitulo6/articulo234.md
    - Artículo 235: capitulo6/articulo235.md
    - Artículo 236: capitulo6/articulo236.md
    - Artículo 237: capitulo6/articulo237.md
    - Artículo 238: capitulo6/articulo238.md
    - Artículo 239: capitulo6/articulo239.md
    - Artículo 240: capitulo6/articulo240.md
    - Artículo 241: capitulo6/articulo241.md
    - Artículo 242: capitulo6/articulo242.md
    - Artículo 243: capitulo6/articulo243.md
    - Artículo 244: capitulo6/articulo244.md
    - Artículo 245: capitulo6/articulo245.md
    - Artículo 246: capitulo6/articulo246.md
    - Artículo 247: capitulo6/articulo247.md
    - Artículo 248: capitulo6/articulo248.md
    - Artículo 249: capitulo6/articulo249.md
    - Artículo 250: capitulo6/articulo250.md
  
  - Poder legislativo:
    - Artículo 251: capitulo7/articulo251.md
    - Artículo 252: capitulo7/articulo252.md
    - Artículo 253: capitulo7/articulo253.md
    - Artículo 254: capitulo7/articulo254.md
    - Artículo 255: capitulo7/articulo255.md
    - Artículo 256: capitulo7/articulo256.md
    - Artículo 257: capitulo7/articulo257.md
    - Artículo 258: capitulo7/articulo258.md
    - Artículo 259: capitulo7/articulo259.md
    - Artículo 260: capitulo7/articulo260.md
    - Artículo 261: capitulo7/articulo261.md
    - Artículo 262: capitulo7/articulo262.md
    - Artículo 263: capitulo7/articulo263.md
    - Artículo 264: capitulo7/articulo264.md
    - Artículo 265: capitulo7/articulo265.md
    - Artículo 266: capitulo7/articulo266.md
    - Artículo 267: capitulo7/articulo267.md
    - Artículo 268: capitulo7/articulo268.md
    - Artículo 269: capitulo7/articulo269.md
    - Artículo 270: capitulo7/articulo270.md
    - Artículo 271: capitulo7/articulo271.md
    - Artículo 272: capitulo7/articulo272.md
    - Artículo 273: capitulo7/articulo273.md
    - Artículo 274: capitulo7/articulo274.md
    - Artículo 275: capitulo7/articulo275.md
    - Artículo 276: capitulo7/articulo276.md
    - Artículo 277: capitulo7/articulo277.md
    - Artículo 278: capitulo7/articulo278.md

  - Poder ejecutivo:
    - Artículo 279: capitulo8/articulo279.md
    - Artículo 280: capitulo8/articulo280.md
    - Artículo 281: capitulo8/articulo281.md
    - Artículo 282: capitulo8/articulo282.md
    - Artículo 283: capitulo8/articulo283.md
    - Artículo 284: capitulo8/articulo284.md
    - Artículo 285: capitulo8/articulo285.md
    - Artículo 286: capitulo8/articulo286.md
    - Artículo 287: capitulo8/articulo287.md
    - Artículo 288: capitulo8/articulo288.md
    - Artículo 289: capitulo8/articulo289.md
    - Artículo 290: capitulo8/articulo290.md
    - Artículo 291: capitulo8/articulo291.md
    - Artículo 292: capitulo8/articulo292.md
    - Artículo 293: capitulo8/articulo293.md
    - Artículo 294: capitulo8/articulo294.md
    - Artículo 295: capitulo8/articulo295.md
    - Artículo 296: capitulo8/articulo296.md
    - Artículo 297: capitulo8/articulo297.md
    - Artículo 298: capitulo8/articulo298.md
    - Artículo 299: capitulo8/articulo299.md
    - Artículo 300: capitulo8/articulo300.md
    - Artículo 301: capitulo8/articulo301.md
    - Artículo 302: capitulo8/articulo302.md
    - Artículo 303: capitulo8/articulo303.md
    - Artículo 304: capitulo8/articulo304.md
    - Artículo 305: capitulo8/articulo305.md
    - Artículo 306: capitulo8/articulo306.md

  - Sistemas de justicia:
    - Artículo 307: capitulo9/articulo307.md
    - Artículo 308: capitulo9/articulo308.md
    - Artículo 309: capitulo9/articulo309.md
    - Artículo 310: capitulo9/articulo310.md
    - Artículo 311: capitulo9/articulo311.md
    - Artículo 312: capitulo9/articulo312.md
    - Artículo 313: capitulo9/articulo313.md
    - Artículo 314: capitulo9/articulo314.md
    - Artículo 315: capitulo9/articulo315.md
    - Artículo 316: capitulo9/articulo316.md
    - Artículo 317: capitulo9/articulo317.md
    - Artículo 318: capitulo9/articulo318.md
    - Artículo 319: capitulo9/articulo319.md
    - Artículo 320: capitulo9/articulo320.md
    - Artículo 321: capitulo9/articulo321.md
    - Artículo 322: capitulo9/articulo322.md
    - Artículo 323: capitulo9/articulo323.md
    - Artículo 324: capitulo9/articulo324.md
    - Artículo 325: capitulo9/articulo325.md
    - Artículo 326: capitulo9/articulo326.md
    - Artículo 327: capitulo9/articulo327.md
    - Artículo 328: capitulo9/articulo328.md
    - Artículo 329: capitulo9/articulo329.md
    - Artículo 330: capitulo9/articulo330.md
    - Artículo 331: capitulo9/articulo331.md
    - Artículo 332: capitulo9/articulo332.md
    - Artículo 333: capitulo9/articulo333.md
    - Artículo 334: capitulo9/articulo334.md
    - Artículo 335: capitulo9/articulo335.md
    - Artículo 336: capitulo9/articulo336.md
    - Artículo 337: capitulo9/articulo337.md
    - Artículo 338: capitulo9/articulo338.md
    - Artículo 339: capitulo9/articulo339.md
    - Artículo 340: capitulo9/articulo340.md
    - Artículo 341: capitulo9/articulo341.md
    - Artículo 342: capitulo9/articulo342.md
    - Artículo 343: capitulo9/articulo343.md
    - Artículo 344: capitulo9/articulo344.md
    - Artículo 345: capitulo9/articulo345.md
    - Artículo 346: capitulo9/articulo346.md
    - Artículo 347: capitulo9/articulo347.md
    - Artículo 348: capitulo9/articulo348.md
    - Artículo 349: capitulo9/articulo349.md

  - Órganos autónomos constitucionales:
    - Artículo 350: capitulo10/articulo350.md
    - Artículo 351: capitulo10/articulo351.md
    - Artículo 352: capitulo10/articulo352.md
    - Artículo 353: capitulo10/articulo353.md
    - Artículo 354: capitulo10/articulo354.md
    - Artículo 355: capitulo10/articulo355.md
    - Artículo 356: capitulo10/articulo356.md
    - Artículo 357: capitulo10/articulo357.md
    - Artículo 358: capitulo10/articulo358.md
    - Artículo 359: capitulo10/articulo359.md
    - Artículo 360: capitulo10/articulo360.md
    - Artículo 361: capitulo10/articulo361.md
    - Artículo 362: capitulo10/articulo362.md
    - Artículo 363: capitulo10/articulo363.md
    - Artículo 364: capitulo10/articulo364.md
    - Artículo 365: capitulo10/articulo365.md
    - Artículo 366: capitulo10/articulo366.md
    - Artículo 367: capitulo10/articulo367.md
    - Artículo 368: capitulo10/articulo368.md
    - Artículo 369: capitulo10/articulo369.md
    - Artículo 370: capitulo10/articulo370.md
    - Artículo 371: capitulo10/articulo371.md
    - Artículo 372: capitulo10/articulo372.md
    - Artículo 373: capitulo10/articulo373.md
    - Artículo 374: capitulo10/articulo374.md
    - Artículo 375: capitulo10/articulo375.md
    - Artículo 376: capitulo10/articulo376.md
    - Artículo 377: capitulo10/articulo377.md
    - Artículo 378: capitulo10/articulo378.md
    - Artículo 379: capitulo10/articulo379.md
    - Artículo 380: capitulo10/articulo380.md
    - Artículo 381: capitulo10/articulo381.md
    - Artículo 382: capitulo10/articulo382.md

  - Reforma y reemplazo de la constitución:
    - Artículo 383: capitulo11/articulo383.md
    - Artículo 384: capitulo11/articulo384.md
    - Artículo 385: capitulo11/articulo385.md
    - Artículo 386: capitulo11/articulo386.md
    - Artículo 387: capitulo11/articulo387.md
    - Artículo 388: capitulo11/articulo388.md

  - Disposiciones transitorias: disposiciones.md
  - Colofón: colofon.md
